
SELECT ft.member_id,
        loan_count,
		loan_amnt,
        avg_loan_amount,
		funded_amnt,
		funded_amnt_inv,
		term,
		int_rate,
        avg_interest_rate,
		installment,
		grade,
		sub_grade,
		emp_title,
		emp_length,
		home_ownership,
		annual_inc,
        avg_annual_income,
		verification_status,
		issue_d,
        loan_status,
        default_rate,
		pymnt_plan,
		purpose,
		title,
		zip_code,
		addr_state,
		dti	delinq_2yrs,
		earliest_cr_line,
		fico_range_low,
		fico_range_high,
		inq_last_6mths,
		mths_since_last_delinq,
		mths_since_last_record,
		open_acc,
		pub_rec,
		revol_bal,
		revol_util,
		total_acc,
		initial_list_status,
		out_prncp,
		out_prncp_inv,
		total_pymnt,
		total_pymnt_inv,
		total_rec_prncp,
        avg_principal_received,
		total_rec_int,
        avg_interest_received,
		total_rec_late_fee,
		recoveries,
		collection_recovery_fee,
		last_pymnt_d,
		last_pymnt_amnt,
		next_pymnt_d,
		last_credit_pull_d,
		last_fico_range_high,
		last_fico_range_low,
		collections_12_mths_ex_med,
		policy_code,
		application_type
FROM amitdb.lending_club_loans AS ft
LEFT JOIN (SELECT member_id,
				COUNT(*) AS loan_count,
				AVG(loan_amnt) AS avg_loan_amount,
				AVG(int_rate) AS avg_interest_rate,
				COUNT(CASE WHEN loan_status = 'Charged Off' THEN 1 END) * 100.0 / COUNT(*) AS default_rate,
				AVG (annual_inc) AS avg_annual_income,
				AVG(total_rec_prncp) AS avg_principal_received,
				AVG(total_rec_int) AS avg_interest_received
			FROM amitdb.lending_club_loans
			GROUP BY member_id) AS ct
ON ft.member_id = ct.member_id
WHERE ft.member_id IS NOT NULL
ORDER BY ft.member_id;
   